DROP TABLE IF EXISTS CityLocation;

CREATE TABLE IF NOT EXISTS
CityLocation(
  id SERIAL PRIMARY KEY NOT NULL,
  city_name VARCHAR(256) NOT NULL UNIQUE,
  display_name VARCHAR(256) NOT NULL UNIQUE,
  latitude VARCHAR(256) NOT NULL,
  longitude VARCHAR(256) NOT NULL
);